// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4TRCrCUpUS1x8MP4DlO4tSAZVIMUpSaE',
    appId: '1:577785883032:web:8ae32e53f8818a6aa623ed',
    messagingSenderId: '577785883032',
    projectId: 'harvest-app-demo-2026',
    authDomain: 'harvest-app-demo-2026.firebaseapp.com',
    storageBucket: 'harvest-app-demo-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAluALoopcFwEN1H3lMZ65gwGnQ4dq54pQ',
    appId: '1:577785883032:android:9a04bb229ccb27bba623ed',
    messagingSenderId: '577785883032',
    projectId: 'harvest-app-demo-2026',
    storageBucket: 'harvest-app-demo-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAisrx15wM8sD9L_zse5GOXwx0dZsoA8Ns',
    appId: '1:577785883032:ios:8573d0f2b74dc145a623ed',
    messagingSenderId: '577785883032',
    projectId: 'harvest-app-demo-2026',
    storageBucket: 'harvest-app-demo-2026.firebasestorage.app',
    iosBundleId: 'com.harvest.harvest',
  );

}